import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Handicap Tracker",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-gray-800 text-white p-4">
          <div className="hidden md:flex space-x-4">

            <Link href="/hdcp">
              Home
            </Link>
            <Link href="/rounds">
              My Handicap info
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
